### PR TITLE
feat: roll to latest tagged chromium on master

### PR DESCRIPTION
**Pull request by nornagon**
This is a stepping-stone towards building against chromium ToT. I haven't fully thought through the implications of this yet, so draft for now.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
I think one thing we may have to rethink here is `master` can **never** be ahead of where we want to branch from for the next major release.  I.e.

`5-0-x` == 73
`master` == 77.canary or something

We want `6-0-x` to be `76`, rolling back in time on master will mean a bunch of features / fixes will be missed in `6-0-x`.  Maybe we need a version number in our `config.yml` on `master` that says

```yml
maximumRollerTarget: 76
```

Or something like that.

Another option is we cut `6-0-x` as soon as `master` would roll past 76 and just use `trop` to ensure everything goes to the correct branches.

Just some things to think about 👍 **but please note that constantly rolling master towards chromium HEAD would be a big win for upgrade cadence**

**Comment by nitsakh** [comment]
Or we could move the `6-0-x` target chromium version ahead.

**Comment by MarshallOfSound** [comment]
> Or we could move the `6-0-x` target chromium version ahead.

That's specifically something we want to avoid as it violates the versioning policy

**Comment by nornagon** [comment]
Why not just take whatever version of chrome is in master when we branch? whatever's there, we get.

**Comment by MarshallOfSound** [comment]
> Why not just take whatever version of chrome is in master when we branch? whatever's there, we get.

If we're constantly rolling forward won't we end up on canary tags? Which won't be stable by the time we want to release electron stable.  One of the things discussed at summit as well was predictable releases

**Comment by nornagon** [comment]
Is that true? Canary -> Stable is ~12 weeks in Chrome. master -> stable is ~12 weeks in Electron I think we'd be fine, then, right?

**Comment by MarshallOfSound** [comment]
> master -> stable is ~12 weeks in Electron

My understanding is we want to be working towards getting considerably faster than 12 weeks 🤔

**Comment by nornagon** [comment]
Sounds like a topic for the next releases WG meeting!

If we did want to reduce the time from master to stable—which I'm not sure that we do—we could maintain a series of `chromium-upgrade/X` branches and merge 1 or 2 versions behind canary into master after the release branch happens.

I do want to think about how we could get automated ToT warnings when things break w.r.t. upstream Chrome though.

**Comment by MarshallOfSound** [comment]
Closing this out as roller does LKGR now 👍

**Pull request closed without merging**
